### ISSUE TITLE
libgeotiff build fails with proj 6.2

### ISSUE THREAD

**Issue by arunisaac** [OSGeo/libgeotiff#26]
libgeotiff fails to build with proj 6.2. I have shown the relevant section of the build log below. I am building libgeotiff using `./configure; make`.

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./libxtiff -I/gnu/store/xadnwgnpxwji8790ckh1swm8282zkl9q-proj-6.2.0/include -DHAVE_LIBPROJ=1 -DHAVE_PROJECTS_H=1 -I/gnu/store/9y286xq1m1aa78hhr48ln5mn2gahrbp3-libtiff-4.0.10/include -DHAVE_TIFF=1 -DCSV_DATA_DIR=\"/gnu/store/49afx1rq91lm0l279lrim3hlwz19pk2g-libgeotiff-1.4.3/share/epsg_csv\" -g -O2 -O3 -DNDEBUG -MT geo_strtod.lo -MD -MP -MF .deps/geo_strtod.Tpo -c geo_strtod.c -o geo_strtod.o >/dev/null 2>&1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./libxtiff -I/gnu/store/xadnwgnpxwji8790ckh1swm8282zkl9q-proj-6.2.0/include -DHAVE_LIBPROJ=1 -DHAVE_PROJECTS_H=1 -I/gnu/store/9y286xq1m1aa78hhr48ln5mn2gahrbp3-libtiff-4.0.10/include -DHAVE_TIFF=1 -DCSV_DATA_DIR=\"/gnu/store/49afx1rq91lm0l279lrim3hlwz19pk2g-libgeotiff-1.4.3/share/epsg_csv\" -g -O2 -O3 -DNDEBUG -MT geotiff_proj4.lo -MD -MP -MF .deps/geotiff_proj4.Tpo -c geotiff_proj4.c  -fPIC -DPIC -o .libs/geotiff_proj4.o
In file included from geotiff_proj4.c:1377:0:
/gnu/store/xadnwgnpxwji8790ckh1swm8282zkl9q-proj-6.2.0/include/proj_api.h:37:2: error: #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
 #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
  ^~~~~
make[2]: *** [Makefile:761: geotiff_proj4.lo] Error 1
make[2]: Leaving directory '/tmp/guix-build-libgeotiff-1.4.3.drv-0/libgeotiff-1.4.3'
make[1]: *** [Makefile:848: all-recursive] Error 1
make[1]: Leaving directory '/tmp/guix-build-libgeotiff-1.4.3.drv-0/libgeotiff-1.4.3'
make: *** [Makefile:605: all] Error 2
```

Thank you for your time! :-)

**Comment by rouault** [comment]
You must use libgeotiff >= 1.5 for PROJ >= 6

**Comment by arunisaac** [comment]
Indeed, sorry for the noise! I somehow messed up with downloading the
correct version.
